// ============================================
// MOCK DATA — Demo mode when Supabase isn't configured
// ============================================

import type { Conversation, Message, AutomationRule, AnalyticsSummary } from '@/types';

export const MOCK_CONVERSATIONS: Conversation[] = [
  {
    id: 'demo-1',
    business_id: 'demo',
    instagram_conversation_id: 'ig-conv-1',
    customer_instagram_id: 'ig-user-1',
    customer_username: 'fashionista_ng',
    customer_name: 'Ada Okafor',
    customer_profile_pic: null,
    status: 'open',
    assigned_to: 'bot',
    last_message_at: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
    last_message_preview: 'How much is the black hoodie?',
    is_read: false,
    tags: ['pricing'],
    customer_email: null,
    customer_phone: null,
    metadata: {},
    created_at: new Date(Date.now() - 3600000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
  },
  {
    id: 'demo-2',
    business_id: 'demo',
    instagram_conversation_id: 'ig-conv-2',
    customer_instagram_id: 'ig-user-2',
    customer_username: 'chiboy_drip',
    customer_name: 'Chidi Nnamdi',
    customer_profile_pic: null,
    status: 'open',
    assigned_to: 'bot',
    last_message_at: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    last_message_preview: 'Yooo this is fire! What sizes for the cargo pants?',
    is_read: true,
    tags: ['comment-to-dm'],
    customer_email: null,
    customer_phone: null,
    metadata: {},
    created_at: new Date(Date.now() - 7200000).toISOString(),
    updated_at: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
  },
  {
    id: 'demo-3',
    business_id: 'demo',
    instagram_conversation_id: 'ig-conv-3',
    customer_instagram_id: 'ig-user-3',
    customer_username: 'temi.styles',
    customer_name: 'Temi Adeleke',
    customer_profile_pic: null,
    status: 'open',
    assigned_to: 'human',
    last_message_at: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
    last_message_preview: 'When will my order arrive?',
    is_read: false,
    tags: ['order-check'],
    customer_email: 'temi@gmail.com',
    customer_phone: null,
    metadata: {},
    created_at: new Date(Date.now() - 86400000).toISOString(),
    updated_at: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'demo-4',
    business_id: 'demo',
    instagram_conversation_id: 'ig-conv-4',
    customer_instagram_id: 'ig-user-4',
    customer_username: 'lagos_baller',
    customer_name: 'Emeka Obi',
    customer_profile_pic: null,
    status: 'open',
    assigned_to: 'bot',
    last_message_at: new Date(Date.now() - 3 * 3600000).toISOString(),
    last_message_preview: 'Do you deliver to Abuja?',
    is_read: true,
    tags: ['delivery'],
    customer_email: null,
    customer_phone: null,
    metadata: {},
    created_at: new Date(Date.now() - 4 * 3600000).toISOString(),
    updated_at: new Date(Date.now() - 3 * 3600000).toISOString(),
  },
  {
    id: 'demo-5',
    business_id: 'demo',
    instagram_conversation_id: 'ig-conv-5',
    customer_instagram_id: 'ig-user-5',
    customer_username: 'midnight_shopper',
    customer_name: 'Kemi Balogun',
    customer_profile_pic: null,
    status: 'open',
    assigned_to: 'bot',
    last_message_at: new Date(Date.now() - 8 * 3600000).toISOString(),
    last_message_preview: 'I want to order the cargo set',
    is_read: true,
    tags: ['after-hours'],
    customer_email: null,
    customer_phone: null,
    metadata: {},
    created_at: new Date(Date.now() - 9 * 3600000).toISOString(),
    updated_at: new Date(Date.now() - 8 * 3600000).toISOString(),
  },
];

export const MOCK_MESSAGES: Record<string, Message[]> = {
  'demo-1': [
    { id: 'm1', conversation_id: 'demo-1', business_id: 'demo', instagram_message_id: null, sender_type: 'customer', content: 'Hey! I saw your page on explore 🔥', message_type: 'text', attachments: [], quick_replies: null, automation_rule_id: null, delivered: true, read: true, created_at: new Date(Date.now() - 5 * 60 * 1000).toISOString() },
    { id: 'm2', conversation_id: 'demo-1', business_id: 'demo', instagram_message_id: null, sender_type: 'customer', content: 'How much is the black hoodie?', message_type: 'text', attachments: [], quick_replies: null, automation_rule_id: null, delivered: true, read: true, created_at: new Date(Date.now() - 4 * 60 * 1000).toISOString() },
    { id: 'm3', conversation_id: 'demo-1', business_id: 'demo', instagram_message_id: null, sender_type: 'bot', content: "Hey! 👋 Thanks for your interest in AuraUp.\n\nThe Essential Hoodie (Black) is ₦28,500.\n\nWe also have it in Charcoal and Cream!\n\n🔗 Shop: auraupstore.com/products/essential-hoodie\n\nWant me to check availability in your size?", message_type: 'text', attachments: [], quick_replies: null, automation_rule_id: 'rule-1', delivered: true, read: true, created_at: new Date(Date.now() - 4 * 60 * 1000 + 2000).toISOString() },
  ],
  'demo-2': [
    { id: 'm4', conversation_id: 'demo-2', business_id: 'demo', instagram_message_id: null, sender_type: 'bot', content: "Yo! 🖤 Thanks for the love on the post.\n\nHere's an exclusive first look at the new collection:\n\n🔗 auraupstore.com/collections/new-arrivals\n\nUse code INNER10 for 10% off your first order. 💪", message_type: 'text', attachments: [], quick_replies: null, automation_rule_id: 'rule-3', delivered: true, read: true, created_at: new Date(Date.now() - 18 * 60 * 1000).toISOString() },
    { id: 'm5', conversation_id: 'demo-2', business_id: 'demo', instagram_message_id: null, sender_type: 'customer', content: 'Yooo this is fire! What sizes do you have for the cargo pants?', message_type: 'text', attachments: [], quick_replies: null, automation_rule_id: null, delivered: true, read: true, created_at: new Date(Date.now() - 15 * 60 * 1000).toISOString() },
  ],
  'demo-3': [
    { id: 'm6', conversation_id: 'demo-3', business_id: 'demo', instagram_message_id: null, sender_type: 'customer', content: 'Hi, I ordered 3 days ago. Order #1047', message_type: 'text', attachments: [], quick_replies: null, automation_rule_id: null, delivered: true, read: true, created_at: new Date(Date.now() - 70 * 60 * 1000).toISOString() },
    { id: 'm7', conversation_id: 'demo-3', business_id: 'demo', instagram_message_id: null, sender_type: 'customer', content: 'When will my order arrive?', message_type: 'text', attachments: [], quick_replies: null, automation_rule_id: null, delivered: true, read: true, created_at: new Date(Date.now() - 69 * 60 * 1000).toISOString() },
    { id: 'm8', conversation_id: 'demo-3', business_id: 'demo', instagram_message_id: null, sender_type: 'bot', content: "📋 Order #1047\n\nItems:\n• Essential Tee (White) x1\n• AuraUp Cap x1\n\nTotal: ₦19,000\nPayment: ✅ Paid\nDelivery: 📦 Shipped!\n\nTracking: LP7829341NG\n🔗 Track: gigl.ng/track/LP7829341NG\n\nShould arrive by tomorrow! 🎉", message_type: 'text', attachments: [], quick_replies: null, automation_rule_id: 'rule-order', delivered: true, read: true, created_at: new Date(Date.now() - 69 * 60 * 1000 + 2000).toISOString() },
    { id: 'm9', conversation_id: 'demo-3', business_id: 'demo', instagram_message_id: null, sender_type: 'human', content: "Hey Temi! Your order is with GIG Logistics and should arrive tomorrow before 4pm. Let us know when it lands! 🖤", message_type: 'text', attachments: [], quick_replies: null, automation_rule_id: null, delivered: true, read: true, created_at: new Date(Date.now() - 62 * 60 * 1000).toISOString() },
  ],
  'demo-4': [
    { id: 'm10', conversation_id: 'demo-4', business_id: 'demo', instagram_message_id: null, sender_type: 'customer', content: 'Do you deliver to Abuja?', message_type: 'text', attachments: [], quick_replies: null, automation_rule_id: null, delivered: true, read: true, created_at: new Date(Date.now() - 3 * 3600000).toISOString() },
    { id: 'm11', conversation_id: 'demo-4', business_id: 'demo', instagram_message_id: null, sender_type: 'bot', content: "📦 Delivery Info:\n\nWe deliver nationwide across Nigeria!\n• Lagos: 1-2 business days\n• Abuja: 2-3 business days\n• Other states: 3-5 business days\n\nDelivery fee to Abuja is ₦3,500.\n\n🔗 Shop now: auraupstore.com", message_type: 'text', attachments: [], quick_replies: null, automation_rule_id: 'rule-2', delivered: true, read: true, created_at: new Date(Date.now() - 3 * 3600000 + 2000).toISOString() },
  ],
  'demo-5': [
    { id: 'm12', conversation_id: 'demo-5', business_id: 'demo', instagram_message_id: null, sender_type: 'customer', content: 'I want to order the cargo set', message_type: 'text', attachments: [], quick_replies: null, automation_rule_id: null, delivered: true, read: true, created_at: new Date(Date.now() - 8 * 3600000).toISOString() },
    { id: 'm13', conversation_id: 'demo-5', business_id: 'demo', instagram_message_id: null, sender_type: 'bot', content: "Hey! 👋 Thanks for reaching out to AuraUp.\n\nWe're currently offline but we'll get back to you first thing in the morning.\n\nIn the meantime, feel free to browse our collection:\n🔗 auraupstore.com\n\nQuiet Strength in Motion. 🖤", message_type: 'text', attachments: [], quick_replies: null, automation_rule_id: 'rule-4', delivered: true, read: true, created_at: new Date(Date.now() - 8 * 3600000 + 2000).toISOString() },
  ],
};

export const MOCK_RULES: AutomationRule[] = [
  {
    id: 'rule-1', business_id: 'demo', name: 'Pricing Inquiry', description: 'Auto-reply when customers ask about prices',
    trigger_type: 'keyword', trigger_config: { type: 'keyword', keywords: ['price', 'how much', 'cost', 'amount', 'pricing'], match_mode: 'fuzzy' },
    response_type: 'single', response: { content: "Hey! 👋 Thanks for your interest in AuraUp.\n\nWhich piece caught your eye? Check out our full collection with prices here:\n🔗 auraupstore.com/collections/all\n\nOr tell me which item you're looking at and I'll send you the details!", message_type: 'text' },
    flow_id: null, is_active: true, priority: 10, cooldown_minutes: 30,
    stats: { triggered_count: 847, last_triggered_at: new Date().toISOString() },
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: 'rule-2', business_id: 'demo', name: 'Delivery Info', description: 'Auto-reply for delivery questions',
    trigger_type: 'keyword', trigger_config: { type: 'keyword', keywords: ['delivery', 'shipping', 'deliver', 'how long', 'ship'], match_mode: 'fuzzy' },
    response_type: 'single', response: { content: "📦 Delivery Info:\n\nWe deliver nationwide across Nigeria!\n• Lagos: 1-2 business days\n• Other states: 3-5 business days\n\nDelivery fee depends on your location. Drop your area and I'll give you an exact quote!\n\n🔗 Shop now: auraupstore.com", message_type: 'text' },
    flow_id: null, is_active: true, priority: 9, cooldown_minutes: 30,
    stats: { triggered_count: 423, last_triggered_at: new Date().toISOString() },
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: 'rule-3', business_id: 'demo', name: 'Comment-to-DM: NEWDROP', description: 'DM users who comment NEWDROP',
    trigger_type: 'comment', trigger_config: { type: 'comment', keywords: ['NEWDROP', 'newdrop', 'NEW'], post_ids: null },
    response_type: 'single', response: { content: "Yo! 🖤 Thanks for the love.\n\nHere's the new collection:\n🔗 auraupstore.com/collections/new-arrivals\n\nUse code INNER10 for 10% off!", message_type: 'text' },
    flow_id: null, is_active: true, priority: 8, cooldown_minutes: 60,
    stats: { triggered_count: 312, last_triggered_at: new Date().toISOString() },
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: 'rule-4', business_id: 'demo', name: 'After Hours', description: 'Away message outside business hours',
    trigger_type: 'after_hours', trigger_config: { type: 'after_hours' },
    response_type: 'single', response: { content: "Hey! 👋 Thanks for reaching out to AuraUp.\n\nWe're currently offline but we'll get back to you first thing in the morning.\n\nQuiet Strength in Motion. 🖤", message_type: 'text' },
    flow_id: null, is_active: true, priority: 100, cooldown_minutes: 60,
    stats: { triggered_count: 156, last_triggered_at: new Date().toISOString() },
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: 'rule-5', business_id: 'demo', name: 'First Message Welcome', description: 'Welcome new customers',
    trigger_type: 'first_message', trigger_config: { type: 'first_message' },
    response_type: 'single', response: { content: "Welcome to AuraUp! 🖤\n\nWe make premium streetwear for those who move with quiet strength.\n\nBrowse: auraupstore.com\nAsk us anything!", message_type: 'text' },
    flow_id: null, is_active: true, priority: 1, cooldown_minutes: 0,
    stats: { triggered_count: 1203, last_triggered_at: new Date().toISOString() },
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: 'rule-6', business_id: 'demo', name: 'Returns & Exchange', description: 'Return policy info',
    trigger_type: 'keyword', trigger_config: { type: 'keyword', keywords: ['return', 'exchange', 'refund', 'wrong size'], match_mode: 'fuzzy' },
    response_type: 'single', response: { content: "We accept returns within 7 days of delivery.\n\nPlease DM us your order number and we'll sort it out.", message_type: 'text' },
    flow_id: null, is_active: false, priority: 7, cooldown_minutes: 30,
    stats: { triggered_count: 89, last_triggered_at: null },
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
];

export const MOCK_ANALYTICS: AnalyticsSummary = {
  period: '7d',
  total_messages_received: 2847,
  total_bot_replies: 2341,
  total_human_replies: 506,
  avg_response_time_seconds: 3,
  automation_rate: 82,
  top_keywords: [
    { keyword: 'price', count: 423 },
    { keyword: 'delivery', count: 287 },
    { keyword: 'size', count: 198 },
    { keyword: 'order', count: 156 },
  ],
  top_automations: [
    { rule_name: 'First Message Welcome', triggered: 1203 },
    { rule_name: 'Pricing Inquiry', triggered: 847 },
    { rule_name: 'Delivery Info', triggered: 423 },
    { rule_name: 'Comment-to-DM: NEWDROP', triggered: 312 },
    { rule_name: 'After Hours', triggered: 156 },
  ],
  conversations_opened: 634,
  conversations_closed: 589,
  emails_collected: 147,
  products_sent: 203,
  hourly_volume: [
    { hour: 0, count: 3 }, { hour: 1, count: 1 }, { hour: 2, count: 0 },
    { hour: 3, count: 0 }, { hour: 4, count: 1 }, { hour: 5, count: 2 },
    { hour: 6, count: 5 }, { hour: 7, count: 12 }, { hour: 8, count: 28 },
    { hour: 9, count: 35 }, { hour: 10, count: 42 }, { hour: 11, count: 38 },
    { hour: 12, count: 31 }, { hour: 13, count: 27 }, { hour: 14, count: 33 },
    { hour: 15, count: 29 }, { hour: 16, count: 22 }, { hour: 17, count: 18 },
    { hour: 18, count: 24 }, { hour: 19, count: 31 }, { hour: 20, count: 28 },
    { hour: 21, count: 15 }, { hour: 22, count: 8 }, { hour: 23, count: 3 },
  ],
};
